on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: "ğŸ’¨ Packing Nuster Turbine for balena"

jobs:
  turbine_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: ğŸ—‚ï¸ Checkout repo
        uses: actions/checkout@v2

      - name: ğŸ—‚ï¸ Checkout NTM repo
        uses: actions/checkout@v2
        with: 
          repository: metalizzsas/NusterTurbineMachines
          ref: main
          path: 'nuster-turbine-machines'
          token: ${{ secrets.GH_TOKEN_2 }}

      - name: ğŸ³ Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: ğŸ³ Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: ğŸ‘·â€â™‚ï¸ Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: â›ï¸ Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: ğŸ§± Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
