name: ğŸš€ Draft release

on:
  pull_request:
    branches:
      - main
env:
  NODE_ENV: development

jobs:
  draft:
    permissions:
      contents: read
      packages: read

    name: Draft release
    runs-on: ubuntu-latest
    if: github.repository == 'metalizzsas/nusterkit' && github.head_ref != 'changeset-release/main'
    steps:
      - name: ğŸ“š Checkout Repo
        uses: actions/checkout@v3

      - name: â›ï¸ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: â›ï¸ Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: â›­ Setup Pnpm github registry to .npmrc
        run: |
          rm .npmrc
          echo "@metalizzsas:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
          echo "node-linker=hoisted" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: ğŸ“š Install Node dependencies
        run: pnpm install --frozen-lockfile --no-optionals

      - name: ğŸ§± Build libraries
        run: pnpm run build:libs

      - name: â” Get Nuster BalenaCloud version from package.json
        id: get_nuster_version
        run: cat ./packages/nuster/package.json | echo version=$(jq -r '.version') >> $GITHUB_OUTPUT

      - name: ğŸ§± Run build scripts on all packages
        run: pnpm run build:packages
        env:
          VITE_NUSTER_VERSION: ${{ steps.get_nuster_version.outputs.version }}

      - name: â†” Replace prod compose file by draft compose file
        run: mv -f docker-compose.draft.yml docker-compose.yml

      - name: â†” Replace prod .dockerignore by draft .dockerignore
        run: mv -f .dockerignore.draft .dockerignore 

      - name: ğŸ³ Create BalenaCloud Release on Beta channel
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: romain_sapet/nusterturbinebeta
          finalize: true
