name: ðŸš€ Draft release

on:
  pull_request:
    branches:
      - main
env:
  NODE_ENV: development

jobs:
  draft:
    permissions:
      contents: read
      packages: read

    name: Draft release
    runs-on: ubuntu-latest
    if: github.repository == 'metalizzsas/nusterkit' && github.head_ref != 'changeset-release/main'
    steps:
      - name: ðŸ“š Checkout Repo
        uses: actions/checkout@v3

      - name: â›ï¸ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: â›ï¸ Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: â›­ Setup Pnpm github registry to .npmrc
        run: |
          rm .npmrc
          echo "@metalizzsas:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: ðŸ“š Install Node dependencies
        run: pnpm install --frozen-lockfile --no-optional

      - name: ðŸ§± Build libraries
        run: pnpm run build:libs

      - name: â” Get Nuster BalenaCloud version from package.json
        id: get_nuster_version
        run: cat ./packages/nuster/package.json | echo version=$(jq -r '.version') >> $GITHUB_OUTPUT

      - name: ðŸ§± Run build scripts on all packages
        run: pnpm run build:packages
        env:
          NODE_ENV: production
          VITE_NUSTER_VERSION: ${{ steps.get_nuster_version.outputs.version }}

      - name: â†” Replace prod turbine dockerfile by draft dockerfile
        run: mv -f ./packages/turbine/Dockerfile.draft.template ./packages/turbine/Dockerfile.template

      - name: â†” Replace prod desktop dockerfile by draft dockerfile
        run: mv -f ./packages/desktop/Dockerfile.draft.template ./packages/desktop/Dockerfile.template

      - name: â†” Replace prod .dockerignore by draft .dockerignore
        run: mv -f .dockerignore.draft .dockerignore 

      - name: ðŸ³ Create BalenaCloud Release on Beta channel
        id: balena_release
        uses: balena-io/deploy-to-balena-action@master
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: romain_sapet/nusterturbine
          finalize: true

      - name: ðŸ³ Set BalenaCloud Draft Release version
        run: >
          curl --request PATCH 
          --url "https://api.balena-cloud.com/v6/release($RELEASE_ID)"
          --header "Authorization: Bearer $BALENA_TOKEN"
          --header "Content-Type: application/json" 
          --data "{\"is_final\": false, \"note\": \"Pull request: $PR_NAME ($PR_ID)\", \"version\": \"$VERSION-$COMMIT\"}"
        env:
          BALENA_TOKEN: ${{ secrets.BALENA_TOKEN }}
          RELEASE_ID: ${{ steps.balena_release.outputs.release_id }}
          PR_ID: ${{ github.event.pull_request.number }}
          PR_NAME: ${{ github.event.pull_request.title }}
          COMMIT: ${{ github.sha }}
          VERSION: ${{ steps.get_nuster_version.outputs.version }}
