on:
  push:
    branches:
      - main

name: "ğŸŒŠ Publishing types package"

jobs:
  turbine_types:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: ğŸ—‚ï¸ Checkout repo
        uses: actions/checkout@v2
      - name: ğŸ‘·â€â™‚ï¸ Setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@metalizzsas'
      - run: npm i --save-dev
      - run: npm run types
      - run: npm publish
        working-directory: types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
